services:    
  backend:
    build:
      target: staging
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - FRONTEND_URL=http://localhost
      - GOOGLE_REDIRECT_URI=http://localhost/api/auth/google/callback
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"