services:
  frontend:
    ports:
      - "80:80"
      - "443:443"
  
  backend:
    build:
      target: staging
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - FRONTEND_URL=https://localhost
      - GOOGLE_REDIRECT_URI=https://localhost/api/auth/google/callback
      - COOKIE_SECURE=true
      - ALLOWED_ORIGINS=["https://localhost"]
  postgres:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"