"""add_is_active_to_media

Revision ID: 03bf4a1567b5
Revises: 1b8628d63922
Create Date: 2025-09-27 23:20:18.025890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bf4a1567b5'
down_revision = '1b8628d63922'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_media_is_active'), 'media', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_is_active'), table_name='media')
    op.drop_column('media', 'is_active')
    # ### end Alembic commands ###