"""add_frames_table_and_update_media_type_enum

Revision ID: 2bd190305f2c
Revises: 03bf4a1567b5
Create Date: 2025-09-28 00:11:15.608679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd190305f2c'
down_revision = '03bf4a1567b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_media_id', sa.UUID(), nullable=False),
    sa.Column('frame_media_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['frame_media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_created_at'), 'frames', ['created_at'], unique=False)
    op.create_index(op.f('ix_frames_frame_media_id'), 'frames', ['frame_media_id'], unique=True)
    op.create_index(op.f('ix_frames_frame_number'), 'frames', ['frame_number'], unique=False)
    op.create_index(op.f('ix_frames_id'), 'frames', ['id'], unique=False)
    op.create_index(op.f('ix_frames_is_active'), 'frames', ['is_active'], unique=False)
    op.create_index(op.f('ix_frames_timestamp_seconds'), 'frames', ['timestamp_seconds'], unique=False)
    op.create_index('ix_frames_video_frame_num', 'frames', ['video_media_id', 'frame_number'], unique=False)
    op.create_index(op.f('ix_frames_video_media_id'), 'frames', ['video_media_id'], unique=False)
    op.create_index('ix_frames_video_timestamp', 'frames', ['video_media_id', 'timestamp_seconds'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_frames_video_timestamp', table_name='frames')
    op.drop_index(op.f('ix_frames_video_media_id'), table_name='frames')
    op.drop_index('ix_frames_video_frame_num', table_name='frames')
    op.drop_index(op.f('ix_frames_timestamp_seconds'), table_name='frames')
    op.drop_index(op.f('ix_frames_is_active'), table_name='frames')
    op.drop_index(op.f('ix_frames_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_frame_number'), table_name='frames')
    op.drop_index(op.f('ix_frames_frame_media_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_created_at'), table_name='frames')
    op.drop_table('frames')
    # ### end Alembic commands ###