"""empty message

Revision ID: d3fb1a74d5fb
Revises: bc0a624b9d36
Create Date: 2025-09-18 22:44:54.675298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fb1a74d5fb'
down_revision = 'bc0a624b9d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'alias', name='unique_doctor_study_alias')
    )
    op.create_index(op.f('ix_studies_created_at'), 'studies', ['created_at'], unique=False)
    op.create_index(op.f('ix_studies_doctor_id'), 'studies', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studies_is_active'), 'studies', ['is_active'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('upload_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type IN ('MediaType.IMAGE', 'MediaType.VIDEO')", name='valid_media_type'),
    sa.CheckConstraint("upload_status IN ('UploadStatus.UPLOADED', 'UploadStatus.PROCESSING', 'UploadStatus.FAILED')", name='valid_upload_status'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_mime_type'), 'media', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_study_id'), 'media', ['study_id'], unique=False)
    op.create_index(op.f('ix_media_upload_status'), 'media', ['upload_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_upload_status'), table_name='media')
    op.drop_index(op.f('ix_media_study_id'), table_name='media')
    op.drop_index(op.f('ix_media_mime_type'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_studies_is_active'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_doctor_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_created_at'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###