"""Initial migration - complete schema

Revision ID: 92a0e66dec74
Revises: 
Create Date: 2025-09-29 21:40:44.049126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a0e66dec74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('matriculation_id', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matriculation_id', name='unique_matriculation_id'),
    sa.UniqueConstraint('user_id', name='unique_doctor_profile')
    )
    op.create_index(op.f('ix_doctor_profiles_id'), 'doctor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_matriculation_id'), 'doctor_profiles', ['matriculation_id'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_status'), 'doctor_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=False)
    op.create_table('studies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'alias', name='unique_doctor_study_alias')
    )
    op.create_index(op.f('ix_studies_created_at'), 'studies', ['created_at'], unique=False)
    op.create_index(op.f('ix_studies_doctor_id'), 'studies', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=False)
    op.create_index(op.f('ix_studies_is_active'), 'studies', ['is_active'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='unique_user_role')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role'), 'user_roles', ['role'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', 'frame', name='mediatype'), nullable=False),
    sa.Column('upload_status', sa.Enum('uploaded', 'processing', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type IN ('image', 'video', 'frame')", name='valid_media_type'),
    sa.CheckConstraint("upload_status IN ('uploaded', 'processing', 'failed')", name='valid_upload_status'),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_created_at'), 'media', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_index(op.f('ix_media_is_active'), 'media', ['is_active'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_mime_type'), 'media', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_study_id'), 'media', ['study_id'], unique=False)
    op.create_index(op.f('ix_media_upload_status'), 'media', ['upload_status'], unique=False)
    op.create_table('frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_media_id', sa.UUID(), nullable=False),
    sa.Column('frame_media_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['frame_media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frames_created_at'), 'frames', ['created_at'], unique=False)
    op.create_index(op.f('ix_frames_frame_media_id'), 'frames', ['frame_media_id'], unique=True)
    op.create_index(op.f('ix_frames_frame_number'), 'frames', ['frame_number'], unique=False)
    op.create_index(op.f('ix_frames_id'), 'frames', ['id'], unique=False)
    op.create_index(op.f('ix_frames_is_active'), 'frames', ['is_active'], unique=False)
    op.create_index(op.f('ix_frames_timestamp_seconds'), 'frames', ['timestamp_seconds'], unique=False)
    op.create_index('ix_frames_video_frame_num', 'frames', ['video_media_id', 'frame_number'], unique=False)
    op.create_index(op.f('ix_frames_video_media_id'), 'frames', ['video_media_id'], unique=False)
    op.create_index('ix_frames_video_timestamp', 'frames', ['video_media_id', 'timestamp_seconds'], unique=False)
    op.create_table('picture_bb_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', 'frame', name='bb_annotation_media_type'), nullable=False),
    sa.Column('bb_class', sa.String(length=100), nullable=False),
    sa.Column('usefulness', sa.Integer(), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('usefulness IN (0, 1)', name='valid_bb_usefulness'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'bb_class', name='unique_media_bb_class_annotation')
    )
    op.create_index(op.f('ix_picture_bb_annotations_bb_class'), 'picture_bb_annotations', ['bb_class'], unique=False)
    op.create_index(op.f('ix_picture_bb_annotations_created_at'), 'picture_bb_annotations', ['created_at'], unique=False)
    op.create_index(op.f('ix_picture_bb_annotations_id'), 'picture_bb_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_picture_bb_annotations_media_id'), 'picture_bb_annotations', ['media_id'], unique=False)
    op.create_index(op.f('ix_picture_bb_annotations_media_type'), 'picture_bb_annotations', ['media_type'], unique=False)
    op.create_table('picture_bb_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', 'frame', name='bb_prediction_media_type'), nullable=False),
    sa.Column('bb_class', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x_min', sa.Float(), nullable=False),
    sa.Column('y_min', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'model_version', 'bb_class', name='unique_media_model_bb_class')
    )
    op.create_index(op.f('ix_picture_bb_predictions_bb_class'), 'picture_bb_predictions', ['bb_class'], unique=False)
    op.create_index(op.f('ix_picture_bb_predictions_created_at'), 'picture_bb_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_picture_bb_predictions_id'), 'picture_bb_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_picture_bb_predictions_media_id'), 'picture_bb_predictions', ['media_id'], unique=False)
    op.create_index(op.f('ix_picture_bb_predictions_media_type'), 'picture_bb_predictions', ['media_type'], unique=False)
    op.create_index(op.f('ix_picture_bb_predictions_model_version'), 'picture_bb_predictions', ['model_version'], unique=False)
    op.create_table('picture_classification_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', 'frame', name='annotation_media_type'), nullable=False),
    sa.Column('usefulness', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('usefulness IN (0, 1)', name='valid_usefulness'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picture_classification_annotations_created_at'), 'picture_classification_annotations', ['created_at'], unique=False)
    op.create_index(op.f('ix_picture_classification_annotations_id'), 'picture_classification_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_picture_classification_annotations_media_id'), 'picture_classification_annotations', ['media_id'], unique=True)
    op.create_index(op.f('ix_picture_classification_annotations_media_type'), 'picture_classification_annotations', ['media_type'], unique=False)
    op.create_table('picture_classification_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', 'frame', name='prediction_media_type'), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'model_version', name='unique_media_model_classification')
    )
    op.create_index(op.f('ix_picture_classification_predictions_created_at'), 'picture_classification_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_picture_classification_predictions_id'), 'picture_classification_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_picture_classification_predictions_media_id'), 'picture_classification_predictions', ['media_id'], unique=False)
    op.create_index(op.f('ix_picture_classification_predictions_media_type'), 'picture_classification_predictions', ['media_type'], unique=False)
    op.create_index(op.f('ix_picture_classification_predictions_model_version'), 'picture_classification_predictions', ['model_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picture_classification_predictions_model_version'), table_name='picture_classification_predictions')
    op.drop_index(op.f('ix_picture_classification_predictions_media_type'), table_name='picture_classification_predictions')
    op.drop_index(op.f('ix_picture_classification_predictions_media_id'), table_name='picture_classification_predictions')
    op.drop_index(op.f('ix_picture_classification_predictions_id'), table_name='picture_classification_predictions')
    op.drop_index(op.f('ix_picture_classification_predictions_created_at'), table_name='picture_classification_predictions')
    op.drop_table('picture_classification_predictions')
    op.drop_index(op.f('ix_picture_classification_annotations_media_type'), table_name='picture_classification_annotations')
    op.drop_index(op.f('ix_picture_classification_annotations_media_id'), table_name='picture_classification_annotations')
    op.drop_index(op.f('ix_picture_classification_annotations_id'), table_name='picture_classification_annotations')
    op.drop_index(op.f('ix_picture_classification_annotations_created_at'), table_name='picture_classification_annotations')
    op.drop_table('picture_classification_annotations')
    op.drop_index(op.f('ix_picture_bb_predictions_model_version'), table_name='picture_bb_predictions')
    op.drop_index(op.f('ix_picture_bb_predictions_media_type'), table_name='picture_bb_predictions')
    op.drop_index(op.f('ix_picture_bb_predictions_media_id'), table_name='picture_bb_predictions')
    op.drop_index(op.f('ix_picture_bb_predictions_id'), table_name='picture_bb_predictions')
    op.drop_index(op.f('ix_picture_bb_predictions_created_at'), table_name='picture_bb_predictions')
    op.drop_index(op.f('ix_picture_bb_predictions_bb_class'), table_name='picture_bb_predictions')
    op.drop_table('picture_bb_predictions')
    op.drop_index(op.f('ix_picture_bb_annotations_media_type'), table_name='picture_bb_annotations')
    op.drop_index(op.f('ix_picture_bb_annotations_media_id'), table_name='picture_bb_annotations')
    op.drop_index(op.f('ix_picture_bb_annotations_id'), table_name='picture_bb_annotations')
    op.drop_index(op.f('ix_picture_bb_annotations_created_at'), table_name='picture_bb_annotations')
    op.drop_index(op.f('ix_picture_bb_annotations_bb_class'), table_name='picture_bb_annotations')
    op.drop_table('picture_bb_annotations')
    op.drop_index('ix_frames_video_timestamp', table_name='frames')
    op.drop_index(op.f('ix_frames_video_media_id'), table_name='frames')
    op.drop_index('ix_frames_video_frame_num', table_name='frames')
    op.drop_index(op.f('ix_frames_timestamp_seconds'), table_name='frames')
    op.drop_index(op.f('ix_frames_is_active'), table_name='frames')
    op.drop_index(op.f('ix_frames_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_frame_number'), table_name='frames')
    op.drop_index(op.f('ix_frames_frame_media_id'), table_name='frames')
    op.drop_index(op.f('ix_frames_created_at'), table_name='frames')
    op.drop_table('frames')
    op.drop_index(op.f('ix_media_upload_status'), table_name='media')
    op.drop_index(op.f('ix_media_study_id'), table_name='media')
    op.drop_index(op.f('ix_media_mime_type'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_is_active'), table_name='media')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_index(op.f('ix_media_created_at'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_studies_is_active'), table_name='studies')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_doctor_id'), table_name='studies')
    op.drop_index(op.f('ix_studies_created_at'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_status'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_matriculation_id'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###